services:
  dataupload:
    build: ./dataupload
    ports:
      - 8001:8001
    env_file: .env
    volumes:
      - ./files:/app/files
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    depends_on:
      - redis

  cron:
    build: 
      context: ./dataupload
      args:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
    command: ["./docker-entrypoint.sh", "cron"]
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7
    ports:
      - 6379:6379

  cron-scripts:
    build: 
      context: scripts
      dockerfile: Dockerfile.cron
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./files:/app/files
