services:
  dataupload:
    build: ./dataupload
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    depends_on:
      - redis

  cron:
    build: ./dataupload
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    command: ["./docker-entrypoint.sh", "cron"]
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7
    ports:
      - 6379:6379

  cron-scripts:
    build: 
      context: scripts
      dockerfile: Dockerfile.cron
    env_file: .env
    volumes:
      - ./logs:/app/logs