services:
  dataupload:
    build: ./dataupload
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    command: >
      bash -c "apt-get update && apt-get install -y cron &&
      python /app/dataupload/manage.py crontab add &&
      daphne -b 0.0.0.0 -p 8001 dataupload.asgi:application"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - 6379:6379
