services:
  dataupload:
    build: ./dataupload
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    command: >
      bash -c "apt-get update && apt-get install -y cron &&
      daphne -b 0.0.0.0 -p 8001 dataupload.asgi:application"
    depends_on:
      - redis
    volumes:
      - ./dataupload:/app
      - ./files:/app/files
      - ./auth:/app/auth  
      - ./logs:/app/logs

  redis:
    image: redis:7
    ports:
      - 6379:6379
