services:
  dataupload:
    build: ./dataupload
    ports:
      - 8001:8001
    env_file: .env
    volumes:
      - ./files:/app/files
      - static-content:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    depends_on:
      - redis

  cron:
    build: 
      context: ./dataupload
      args:
        - DB_HOST
        - DB_NAME
        - DB_PASS
        - DB_PORT
        - DB_USER
    environment:
      - DJANGO_SETTINGS_MODULE=dataupload.settings
      - PYTHONPATH=/app
    command: ["./docker-entrypoint.sh", "cron"]
    volumes:
      - ./logs:/app/logs
      - static-content:/app/dataupload/media
  

  redis:
      image: redis:7-alpine
      command: redis-server --requirepass $REDIS_PASSWORD
      ports:
        - "6379:6379"

  cron-scripts:
    build: 
      context: scripts
      dockerfile: Dockerfile.cron
      args:
        - GOOGLE_CREDENTIALS
        - DB_HOST
        - DB_NAME
        - DB_PASS
        - DB_PORT
        - DB_USER
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./files:/app/files

volumes:
  static-content:
