# Generated by Django 4.0.5 on 2022-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bevtelek',
            fields=[
                ('azonosito', models.TextField(blank=True, db_column='Azonosito', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('teljesites_datuma', models.DateField(blank=True, db_column='Teljesites_datuma', null=True)),
                ('ar', models.FloatField(blank=True, db_column='Ar', null=True)),
                ('penznem', models.TextField(blank=True, db_column='Penznem', null=True)),
                ('atvaltasi_rata', models.BigIntegerField(blank=True, db_column='Atvaltasi_rata', null=True)),
                ('afa_field', models.BigIntegerField(blank=True, db_column='AFA_', null=True)),
                ('osszesen_huf', models.FloatField(blank=True, db_column='Osszesen_HUF', null=True)),
                ('netto_ossz', models.FloatField(blank=True, db_column='Netto_ossz', null=True)),
                ('afa_ertek', models.BigIntegerField(blank=True, db_column='AFA_ertek', null=True)),
                ('tipus', models.TextField(blank=True, db_column='Tipus', null=True)),
                ('penztarca', models.TextField(blank=True, db_column='Penztarca', null=True)),
                ('kategoria', models.TextField(blank=True, db_column='Kategoria', null=True)),
                ('eredmeny_kategoria', models.TextField(blank=True, db_column='Eredmeny_kategoria', null=True)),
                ('tranzakcio_uzenet', models.TextField(blank=True, db_column='Tranzakcio_uzenet', null=True)),
                ('tranzakcio_partner_fiok', models.TextField(blank=True, db_column='Tranzakcio_partner_fiok', null=True)),
                ('tranzakcio_beszallito_neve', models.TextField(blank=True, db_column='Tranzakcio_beszallito_neve', null=True)),
                ('tranzakcio_tipusa', models.TextField(blank=True, db_column='Tranzakcio_tipusa', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bevÚtelek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatauploadBevtelek',
            fields=[
                ('azonosito', models.TextField(db_column='Azonosito', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('teljesites_datuma', models.TextField(blank=True, db_column='Teljesites_datuma', null=True)),
                ('ar', models.FloatField(blank=True, db_column='Ar', null=True)),
                ('penznem', models.TextField(blank=True, db_column='Penznem', null=True)),
                ('atvaltasi_rata', models.BigIntegerField(blank=True, db_column='Atvaltasi_rata', null=True)),
                ('afa_field', models.BigIntegerField(blank=True, db_column='AFA_', null=True)),
                ('osszesen_huf', models.FloatField(blank=True, db_column='Osszesen_HUF', null=True)),
                ('netto_ossz', models.FloatField(blank=True, db_column='Netto_ossz', null=True)),
                ('afa_ertek', models.BigIntegerField(blank=True, db_column='AFA_ertek', null=True)),
                ('tipus', models.TextField(blank=True, db_column='Tipus', null=True)),
                ('penztarca', models.TextField(blank=True, db_column='Penztarca', null=True)),
                ('kategoria', models.TextField(blank=True, db_column='Kategoria', null=True)),
                ('eredmeny_kategoria', models.TextField(blank=True, db_column='Eredmeny_kategoria', null=True)),
                ('tranzakcio_uzenet', models.TextField(blank=True, db_column='Tranzakcio_uzenet', null=True)),
                ('tranzakcio_partner_fiok', models.TextField(blank=True, db_column='Tranzakcio_partner_fiok', null=True)),
                ('tranzakcio_beszallito_neve', models.TextField(blank=True, db_column='Tranzakcio_beszallito_neve', null=True)),
                ('tranzakcio_tipusa', models.TextField(blank=True, db_column='Tranzakcio_tipusa', null=True)),
                ('id', models.IntegerField()),
            ],
            options={
                'db_table': 'dataupload_bevÚtelek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatauploadDatabaseconnections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('host', models.CharField(max_length=150)),
                ('database', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('port', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dataupload_databaseconnections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatauploadImporttemplates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=30)),
                ('special_query', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dataupload_importtemplates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatauploadTabletemplates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=30)),
                ('pkey_col', models.CharField(max_length=30)),
                ('skiprows', models.CharField(max_length=10)),
                ('append', models.BooleanField()),
                ('database', models.CharField(max_length=40)),
                ('extension_format', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dataupload_tabletemplates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatauploadUploadmodel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('extension_format', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dataupload_uploadmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlsElszmols',
            fields=[
                ('csomagszam', models.TextField(blank=True, db_column='Csomagszam', null=True)),
                ('ugyfel_hivatkozas_field', models.TextField(blank=True, db_column='Ugyfel_hivatkozas_', null=True)),
                ('utanvet_hivatkozas_field', models.TextField(blank=True, db_column='Utanvet_hivatkozas_', null=True)),
                ('utanvet_osszege', models.FloatField(blank=True, db_column='Utanvet_osszege', null=True)),
                ('felvetel_datuma_field', models.DateTimeField(blank=True, db_column='Felvetel_datuma_', null=True)),
                ('kiszallitas_napja', models.DateTimeField(blank=True, db_column='Kiszallitas_napja', null=True)),
                ('celorszag_field', models.TextField(blank=True, db_column='Celorszag_', null=True)),
                ('suly', models.FloatField(blank=True, db_column='Suly', null=True)),
                ('kapcsolt_szolgaltatasok', models.TextField(blank=True, db_column='Kapcsolt_szolgaltatasok', null=True)),
                ('futar_koltseg', models.FloatField(blank=True, db_column='Futar_koltseg', null=True)),
                ('cimzett_neve_field', models.TextField(blank=True, db_column='Cimzett_neve_', null=True)),
                ('kiszallitasi_cim_field', models.TextField(blank=True, db_column='Kiszallitasi_cim_', null=True)),
                ('atvevo_neve_field', models.TextField(blank=True, db_column='Atvevo_neve_', null=True)),
                ('logisztika', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gls_elszßmolßs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kltsgek',
            fields=[
                ('azonosito', models.TextField()),
                ('honap', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('partner', models.TextField(blank=True, null=True)),
                ('koltsegelem', models.TextField(blank=True, null=True)),
                ('ar', models.FloatField(blank=True, null=True)),
                ('penznem', models.TextField(blank=True, null=True)),
                ('atvaltasi_rata', models.BigIntegerField(blank=True, null=True)),
                ('afa_field', models.BigIntegerField(blank=True, db_column='afa_', null=True)),
                ('osszesen_huf', models.FloatField(blank=True, null=True)),
                ('netto_ossz', models.FloatField(blank=True, null=True)),
                ('afa_ertek', models.FloatField(blank=True, null=True)),
                ('tipus', models.TextField(blank=True, null=True)),
                ('penztarca', models.TextField(blank=True, null=True)),
                ('koltseg_osztaly', models.TextField(blank=True, null=True)),
                ('iktatasi_allapot', models.TextField(blank=True, null=True)),
                ('szamla_sorszama', models.FloatField(blank=True, null=True)),
                ('tranzakcio_uzenet', models.TextField(blank=True, null=True)),
                ('tranzakcio_partner_fiok', models.TextField(blank=True, null=True)),
                ('tranzakcio_beszallito_neve', models.TextField(blank=True, null=True)),
                ('tranzakcio_tipusa', models.TextField(blank=True, null=True)),
                ('teljesites_datuma', models.DateField(blank=True, null=True)),
                ('megjegyzesek', models.TextField(blank=True, null=True)),
                ('tranzakcio_belso_azonosito', models.TextField(blank=True, null=True)),
                ('tranzakcio_kulso_azonosito', models.TextField(blank=True, null=True)),
                ('megjegyzesek2', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'k÷ltsÚgek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StartingClosingCf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.TextField(blank=True, null=True)),
                ('starting_values', models.BigIntegerField(blank=True, null=True)),
                ('closing_values', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'starting_closing_cf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Szmlk',
            fields=[
                ('szamla_belso_azonosito', models.TextField(db_column='Szamla_belso_azonosito')),
                ('szamla_azonosito', models.TextField(blank=True, db_column='Szamla_azonosito', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('hatarido', models.TextField(blank=True, db_column='Hatarido', null=True)),
                ('fizetes_datuma', models.TextField(blank=True, db_column='Fizetes_datuma', null=True)),
                ('teljesites_datuma', models.TextField(blank=True, db_column='Teljesites_datuma', null=True)),
                ('tipus', models.TextField(blank=True, db_column='Tipus', null=True)),
                ('fizetesi_allapot', models.TextField(blank=True, db_column='Fizetesi_allapot', null=True)),
                ('iktatasi_allapot', models.TextField(blank=True, db_column='Iktatasi_Allapot', null=True)),
                ('expired', models.BooleanField(blank=True, db_column='Expired', null=True)),
                ('partner', models.TextField(blank=True, db_column='Partner', null=True)),
                ('szallitmanyok', models.TextField(blank=True, db_column='Szallitmanyok', null=True)),
                ('koltseg', models.FloatField(blank=True, db_column='Koltseg', null=True)),
                ('penznem', models.TextField(blank=True, db_column='Penznem', null=True)),
                ('atvaltasi_rata', models.FloatField(blank=True, db_column='Atvaltasi_rata', null=True)),
                ('osszesen_huf', models.FloatField(blank=True, db_column='Osszesen_HUF', null=True)),
                ('pdf', models.TextField(blank=True, db_column='PDF', null=True)),
                ('fizetesi_mod', models.TextField(blank=True, db_column='Fizetesi_mod', null=True)),
                ('megjegyzes', models.TextField(blank=True, db_column='Megjegyzes', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'szßmlßk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistBlacklistedtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistOutstandingtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('jti', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bevételek',
        ),
        migrations.DeleteModel(
            name='DatabaseConnections',
        ),
        migrations.DeleteModel(
            name='GlsElszámols',
        ),
        migrations.DeleteModel(
            name='ImportTemplates',
        ),
        migrations.DeleteModel(
            name='Költségek',
        ),
        migrations.DeleteModel(
            name='Számlák',
        ),
        migrations.DeleteModel(
            name='TableTemplates',
        ),
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
