# Generated by Django 4.0.6 on 2022-08-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_folorderbase_folorderetc_folorderfee_folorderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proorderbase',
            table='pro_order_base',
        ),
        migrations.AlterModelTable(
            name='proorderetc',
            table='pro_order_fee',
        ),
        migrations.AlterModelTable(
            name='proorderfee',
            table='pro_order_fee',
        ),
        migrations.AlterModelTable(
            name='proorderitem',
            table='pro_order_item',
        ),
        migrations.AlterModelTable(
            name='proordershippingfee',
            table='pro_order_shipping_fee',
        ),
        migrations.AlterModelTable(
            name='proreturnorder',
            table='pro_return_order',
        ),
        migrations.AlterModelTable(
            name='proreturnorderitem',
            table='pro_return_order_item',
        ),
        migrations.AlterModelTable(
            name='proreturnordershippingfee',
            table='pro_return_order_shipping_fee',
        ),
        migrations.AlterModelTable(
            name='prostockaging',
            table='pro_stock_aging',
        ),
        migrations.AlterModelTable(
            name='prostocktransactionreport',
            table='pro_stock_transaction_report',
        ),
    ]
