# Generated by Django 4.0.6 on 2022-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_folorderbase_folorderetc_folorderfee_folorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatauploadUploadchecker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=50)),
                ('file', models.FileField(max_length=200, upload_to='upload_files/')),
                ('user_id', models.IntegerField()),
                ('file_extension_status', models.TextField(blank=True, null=True)),
                ('header_status', models.TextField(blank=True, null=True)),
                ('column_content_status', models.TextField(blank=True, null=True)),
                ('overall_status', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'dataupload_uploadchecker',
                'managed': False,
            },
        ),
    ]
