# Generated by Django 4.0.6 on 2022-09-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_proorderbase_table_alter_proorderetc_table_and_more'),
        ('api', '0007_datauploaduploadchecker'),
    ]

    operations = [
    ]
