# Generated by Django 4.0.6 on 2022-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20220905_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatauploadTableOverview',
            fields=[
                ('db_table', models.CharField(max_length=255)),
                ('verbose_name', models.CharField(max_length=255)),
                ('available_at', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dataupload_tableoverview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('url', models.TextField()),
                ('table', models.TextField()),
                ('user_id', models.IntegerField()),
                ('frequency', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolLearnDash',
            fields=[
                ('Sku', models.TextField()),
                ('Billing_First_Name', models.TextField()),
                ('Billing_Last_Name', models.TextField()),
                ('Billing_Email', models.TextField()),
                ('Product_Name', models.TextField()),
                ('Unit_Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Order_Date', models.DateField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('learn_dash_id', models.IntegerField()),
                ('Order_Id', models.TextField()),
            ],
            options={
                'db_table': 'fol_learn_dash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProProducts',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True)),
                ('minimum_stock_quantity', models.FloatField(blank=True, db_column='Minimum_Stock_Quantity', null=True)),
                ('optimal_stock_quantity', models.FloatField(blank=True, db_column='Optimal_Stock_Quantity', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('product_class', models.FloatField(blank=True, db_column='Product_Class', null=True)),
                ('tags', models.TextField(blank=True, db_column='Tags', null=True)),
                ('warehouse_fo_raktar_minimum_stock_quantity', models.FloatField(blank=True, db_column='Warehouse___Fo_raktar___Minimum_Stock_Quantity', null=True)),
                ('warehouse_fo_raktar_optimal_stock_quantity', models.FloatField(blank=True, db_column='Warehouse___Fo_raktar___Optimal_Stock_Quantity', null=True)),
                ('warehouse_selejt_raktar_minimum_stock_quantity', models.FloatField(blank=True, db_column='Warehouse___Selejt_raktar___Minimum_Stock_Quantity', null=True)),
                ('warehouse_selejt_raktar_optimal_stock_quantity', models.FloatField(blank=True, db_column='Warehouse___Selejt_raktar___Optimal_Stock_Quantity', null=True)),
            ],
            options={
                'db_table': 'pro_products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatauploadDatabaseconnections',
        ),
        migrations.DeleteModel(
            name='DatauploadImporttemplates',
        ),
        migrations.DeleteModel(
            name='DatauploadUploadchecker',
        ),
        migrations.AlterModelTable(
            name='folorderitem',
            table='fol_order_item',
        ),
    ]
