# Generated by Django 4.0.6 on 2022-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_datauploadtableoverview_feed_follearndash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatauploadGroups',
            fields=[
                ('group', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tables', models.TextField(blank=True, null=True)),
                ('user_ids', models.TextField()),
            ],
            options={
                'db_table': 'dataupload_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolArresFigyelo',
            fields=[
                ('Order_Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unit_price', models.FloatField()),
                ('order_fee', models.FloatField()),
                ('netto_szallitasi_dij', models.FloatField()),
                ('discount_value', models.FloatField()),
                ('netto_osszesen', models.FloatField()),
                ('futar_koltseg', models.FloatField()),
                ('logisztikai_szolgaltatas', models.FloatField()),
                ('csomagolo_anyag', models.FloatField()),
                ('order_ctn_ev', models.FloatField()),
                ('elabe', models.FloatField()),
                ('egyeb_koltseg', models.FloatField()),
                ('Order_Date', models.DateField()),
            ],
            options={
                'db_table': 'fol_arres_figyelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolCF',
            fields=[
                ('honap', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nyito', models.IntegerField()),
                ('bevetel', models.FloatField()),
                ('zaro', models.FloatField()),
                ('cashflow', models.FloatField()),
                ('kiadas', models.FloatField()),
                ('afa_bejovo', models.FloatField()),
                ('afa_kimeno', models.FloatField()),
                ('befizetes', models.FloatField()),
            ],
            options={
                'db_table': 'fol_cf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolFedezet',
            fields=[
                ('month', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('allando_koltsegek', models.FloatField()),
                ('egyeb_koltsegek', models.FloatField()),
                ('valtozo_koltsegek', models.FloatField()),
                ('orders', models.FloatField()),
                ('total', models.FloatField()),
                ('ads', models.FloatField()),
                ('facebook', models.FloatField()),
                ('logisztika', models.FloatField()),
                ('elabe', models.FloatField()),
                ('netto_osszesen', models.FloatField()),
                ('arres', models.FloatField()),
                ('arres_szazalek', models.FloatField()),
                ('marketing_es_pr', models.FloatField()),
            ],
            options={
                'db_table': 'fol_fedezet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolGlsOsszesites',
            fields=[
                ('ugyfel_hivatkozas', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('csomagszam', models.IntegerField()),
                ('suly', models.FloatField()),
                ('gls', models.FloatField()),
                ('webshop', models.FloatField()),
                ('net_gls', models.FloatField()),
                ('orderid', models.CharField(max_length=30)),
                ('feladas_datuma', models.DateTimeField()),
            ],
            options={
                'db_table': 'fol_gls_összesítés',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolOrdersÖsszesítő',
            fields=[
                ('date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('orders', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'fol_orders_összesítő',
                'managed': False,
            },
        ),
    ]
