# Generated by Django 4.0.6 on 2022-07-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datastudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnections',
            name='created_by',
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
