# Generated by Django 4.0.6 on 2022-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0002_remove_databaseconnections_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnections',
            name='port',
            field=models.CharField(default=25060, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseconnections',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
