# Generated by Django 4.0.6 on 2022-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0005_importtemplates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importtemplates',
            old_name='query',
            new_name='special_query',
        ),
        migrations.AlterField(
            model_name='importtemplates',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
