# Generated by Django 4.0.6 on 2022-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0006_rename_query_importtemplates_special_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtemplates',
            name='special_query',
            field=models.CharField(max_length=1000),
        ),
    ]
