# Generated by Django 4.0.6 on 2022-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0008_tabletemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletemplates',
            name='table',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
