# Generated by Django 4.0.6 on 2022-07-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0009_alter_tabletemplates_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletemplates',
            name='append',
        ),
    ]
