# Generated by Django 4.0.6 on 2022-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0010_remove_tabletemplates_append'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemplates',
            name='append',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
