# Generated by Django 4.0.6 on 2022-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0011_tabletemplates_append'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('file', models.FileField(max_length=200, upload_to='upload_files/%Y/%m/%d/')),
            ],
        ),
    ]
