# Generated by Django 4.0.6 on 2022-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0012_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='database',
            field=models.CharField(default='main-frankfurt', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(max_length=200, upload_to='upload_files/'),
        ),
    ]
