# Generated by Django 4.0.6 on 2022-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0013_uploadmodel_database_alter_uploadmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='user_id',
            field=models.IntegerField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
