# Generated by Django 4.0.6 on 2022-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0014_uploadmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
