# Generated by Django 4.0.6 on 2022-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0015_alter_uploadmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemplates',
            name='database',
            field=models.CharField(default='main-frankfurt', max_length=40),
            preserve_default=False,
        ),
    ]
