# Generated by Django 4.0.6 on 2022-07-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0016_tabletemplates_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='database',
        ),
    ]
