# Generated by Django 4.0.6 on 2022-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0018_uploadmodel_extension_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='extension_format',
        ),
    ]
