# Generated by Django 4.0.6 on 2022-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0019_remove_uploadmodel_extension_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemplates',
            name='extension_format',
            field=models.CharField(default='xlsx', max_length=10),
            preserve_default=False,
        ),
    ]
